version: '3.8'
services:
  web_interface:
    build: ./web_interface
    ports:
      - "80:3001"
    networks:
      - app_network

  flask_stix_vulnerability:
    build: ./flask_stix_vulnerability
    ports:
      - "5000:5001"
    networks:
      - app_network

  flask_vulnerability:
    build: ./flask_vulnerability
    ports:
      - "5001:5002"
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - web_interface
      - flask_stix_vulnerability
      - flask_vulnerability

networks:
  app_network:
    driver: bridge
