version: 'v2.26.1'
services:
  web_interface:
    build: ./webInterface
    volumes:
      - type: bind
        source: ./webInterface/src
        target: /webInterface/src
    #ports:
    #  - "80:3001"
    networks:
      - app_network

  stix_and_vulnerability:
    build: ./stix&vulnerability
    volumes:
        - type: bind
          source: ./stix&vulnerability
          target: /stix&vulnerability
    #ports:
    #  - "5002:5002"
    networks:
      - app_network

  cvwelib:
    build: ./cvwelib
    volumes:
      - type: bind
        source: ./cvwelib
        target: /cvwelib
    #ports:
    #  - "5001:5001"
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - web_interface
      - stix_and_vulnerability
      - cvwelib

networks:
  app_network:
    driver: bridge
