version: 'v2.26.1'
services:
  web_interface:
    build: ./web_interface
    ports:
      - "80:3001"
    networks:
      - app_network

  stix&vulnerability:
    build: ./stix&vulnerability
    ports:
      - "5002:5002"
    networks:
      - app_network

  cvwelib:
    build: ./cvwelib
    ports:
      - "5001:5001"
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - webInterface
      - stix&vulnerability
      - cvwelib

networks:
  app_network:
    driver: bridge
